language: haskell
ghc:
  - 7.6
  - 7.8
install:
  - sudo apt-get update -qq
  - sudo apt-get install libsndfile-dev libsamplerate0-dev libmp3lame-dev
  - cabal install alex happy
  - cabal install c2hs
script:
  - cabal install ./conduit-audio ./conduit-audio-lame ./conduit-audio-sndfile ./conduit-audio-samplerate
  - ghc test.hs -Wall
